---
# YAML documents begin with the document separator ---
# The minus in YAML this indicates a list item. The Playbook contains a list
# of plays, with each play being a dictionary

- name: 'registering variables in the play to validate and display the output of the play'

  # Target: where our play will run and options it will run with
  hosts: all
  gather_facts: true
  # Task: the list of tasks that will be executed within the playbook
  tasks:       
     - name: Capturing the output using register directive
       command: hostname -s
       when: (ansible_distribution == "OracleLinux" and ansible_distribution_major_version == "7") or
             (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14")

# Three dots indicate the end of a YAML document
...
